spring:
  data:
    mongodb:
      authentication-database: admin
#      username: myUserAdmin
#      password: abc123
      database: boklib
      port: 27017
#      host: 176.57.220.30
      host: localhost

