DROP TABLE IF EXISTS COMMENTS;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS USERS;

CREATE TABLE AUTHORS(
    AUTHOR_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NICKNAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255),
    FIRST_NAME VARCHAR(255),
    MIDDLE_NAME VARCHAR(255)
);

CREATE TABLE GENRES(
    GENRE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    GENRE VARCHAR(255) NOT NULL
);

CREATE TABLE BOOKS(
    BOOK_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    PAGE_COUNT NUMBER NOT NULL,
    AUTHOR_ID BIGINT NOT NULL,
    GENRE_ID BIGINT NOT NULL,
    CONSTRAINT BOOKS_AUTHORS FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID),
    CONSTRAINT BOOKS_GENRES FOREIGN KEY (GENRE_ID) REFERENCES GENRES(GENRE_ID)
);

CREATE TABLE COMMENTS(
    COMMENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    MESSAGE VARCHAR(2000) NOT NULL,
    BOOK_ID BIGINT,
    CONSTRAINT BOOK_COMMENT FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID)
);

CREATE TABLE USERS(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(2000) NOT NULL,
    PASSWORD VARCHAR(2000) NOT NULL
);
