logging:
  level:
    org: ERROR
    com: ERROR
  file:
    name: app.log
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.17.40.124:5433/postgres
    username: postgres
    password: postgres
